// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function f(v, _u) {
  return v;
}

console.log("Hello, BuckleScript");

var v = 3;

exports.v = v;
exports.f = f;
/*  Not a pure module */
