// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Demo = require("./demo.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");

function f(v, _u) {
  return Curry._2(v, (function (prim) {
                console.log(prim);
                
              }), "hello");
}

var v = Demo.v;

exports.v = v;
exports.f = f;
/* Demo Not a pure module */
